= Arquillian GlassFish Container Integration

> NOTE: This repository is my fork of the official https://github.com/arquillian/arquillian-container-glassfish6[arquillian-container-glassfish6].

*WARNING: Please use https://github.com/OmniFish-EE/arquillian-container-glassfish[OmniFish EE Arquillian Glassfish] as the replacement if you encountered some issues.*

image::https://github.com/hantsy/arquillian-container-glassfish-jakarta/actions/workflows/build.yml/badge.svg[Build Status,link=https://github.com/hantsy/arquillian-container-glassfish-jakarta/actions/workflows/build.yml]

The upstream project is inactive, so I decided to fork it and update it to the latest GlassFish 7.0 and Jakarta EE 10.

* Update to Glassfish 7.0 and Jakarta EE 10 APIs.
* Rename project artifactIds and add a `-jakarta` postfix.
* Change the build baseline Java version to Java 11, and clean the source codes.
* Update the testing codes to the latest Arquillian Core 1.7.x and JUnit 5.

== Usage

*This project is not published to the Maven Central repository*. I choose https://jitpack.io[JitPack] to share my work to Java communities.

Add the following repository to your project pom.xml.

```xml
<repositories>
    //... other repositories
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```

To use the *Managed GlassFish Container Adapter*, add the following dependency.

```xml
<dependencies>
    // other dependencies
    <dependency>
        <groupId>com.github.hantsy.arquillian-container-glassfish-jakarta</groupId>
        <artifactId>arquillian-glassfish-managed-jakarta</artifactId>
        <version>${arquillian-glassfish-jakarta.version}</version>
        <scope>test</scope>
    </dependency>
</dependencies>
```

Alternatively, to use *Remote GlassFish Container Adapter*, add the following dependency.

```xml
<dependencies>
    // other dependencies
    <dependency>
        <groupId>com.github.hantsy.arquillian-container-glassfish-jakarta</groupId>
        <artifactId>arquillian-glassfish-remote-jakarta</artifactId>
        <version>${arquillian-glassfish-jakarta.version}</version>
        <scope>test</scope>
    </dependency>
</dependencies>
```

Configure property `arquillian-glassfish-arquillian.version`, check the latest build version from https://jitpack.io/#hantsy/arquillian-container-glassfish-jakarta[JitPack Build Status] page.

```xml
<properties>
    //other properties
    <arquillian-glassfish-jakarta.version>1665e14a</arquillian-glassfish-jakarta.version>
</properties>    
```    

Explore my https://github.com/hantsy/jakartaee10-sandbox[Jakarta EE 10 Example Codes] and get to know the Arquillian configuration details.

> NOTE: If you are new to Arquillian, go to https://github.com/hantsy/jakartaee9-starter-boilerplate[Jakarta EE Starter Boilerplate] project to study it yourself.

== Build

Clone the project and run the following command in the project root folder:

```bash
mvn clean install
```
