= Arquillian GlassFish Container Integration

> NOTE: This repository is my fork of the official https://github.com/arquillian/arquillian-container-glassfish6[arquillian-container-glassfish6].

*WARNING: Please use https://github.com/OmniFish-EE/arquillian-container-glassfish[OmniFish EE Arquillian Glassfish] as the replacement if you encountered some issues.*

image::https://github.com/hantsy/arquillian-container-glassfish-jakarta/actions/workflows/build.yml/badge.svg[Build Status,link=https://github.com/hantsy/arquillian-container-glassfish-jakarta/actions/workflows/build.yml]

The upstream project is inactive, so I decided to fork it and update it to the latest GlassFish 7.0 and Jakarta EE 10.

* Update to Glassfish 7.0 and Jakarta EE 10 APIs.
* Rename project group ID(required when publishing to Maven Central).
* Change the build baseline Java version to Java 11, and clean the source codes.
* Update the testing codes to the latest Arquillian Core 1.7.x and JUnit 5.

== Usage

__For the versions prior to 7.0.12, please refer link:JITPACK.adoc[Configure JITPack Repository] to setup project__.

Since 7.0.13, the artifacts have been published in the Maven Central Repository.

Add the following dependency to use the *Managed GlassFish Container Adapter*.

```xml
<dependencies>
    // other dependencies
    <dependency>
        <groupId>io.github.hantsy.arquillian</groupId>
        <artifactId>arquillian-glassfish-managed</artifactId>
        <version>${arquillian-glassfish.version}</version>
        <scope>test</scope>
    </dependency>
</dependencies>
```

Alternatively, add the following dependency to use *Remote GlassFish Container Adapter*.

```xml
<dependencies>
    // other dependencies
    <dependency>
        <groupId>io.github.hantsy.arquillian</groupId>
        <artifactId>arquillian-glassfish-remote</artifactId>
        <version>${arquillian-glassfish.version}</version>
        <scope>test</scope>
    </dependency>
</dependencies>
```

Explore my https://github.com/hantsy/jakartaee10-sandbox[Jakarta EE 10 Example Codes] and get to know the Arquillian configuration details.

> NOTE: If you are new to Arquillian, go to https://github.com/hantsy/jakartaee9-starter-boilerplate[Jakarta EE Starter Boilerplate] project to study it yourself.

== Build

Clone the project and run the following command in the project root folder:

```bash
mvn clean install
```
