services:
  glassfish7:
    image: omnifish/glassfish:7.0.14
    profiles: ["gf7"]
    ports:
      - "8080:8080"
      - "4848:4848"

  glassfish8:
    image: ghcr.io/eclipse-ee4j/glassfish:8.0.2
    profiles: ["gf8"]
    ports:
      - "8081:8080"
      - "4849:4848"
