name: Build

on:
  push:
    paths:
      - "glassfish-*/**"
      - "pom.xml"
    branches:
      - master
      - 'refactor/**'
      - 'fix/**'
      - 'feature/**'
      - 'chore/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
          cache: "maven"
      - name: Build with Maven (skip tests)
        run: ./mvnw -B install -DskipTests --file pom.xml
